# Usage info: https://wiki.hyphale.com/contributing/setup/server-setup/#auto-download-plugins
#
# Prefer URLs in this order:
# - GitHub
# - Modrinth
# - Selfhosted on Hyphale
# - Avoid any other source
#
# Notes:
# - Don't use public links for premium plugins, use the rclone format instead
paper {
  # Plugins we often depend upon
  core {
    mono: "github:Hyphale/Monolith-Paper:v0.81.0:.*jar"
//    sqlpool: "nexus:com.hyphale:SQLPool-Bukkit:0.1.*"
//    soundeffectfactory: "nexus:com.hyphale:SoundEffectFactory-Bukkit:0.4.*"
//    goliath: "nexus:com.hyphale:Goliath-Bukkit:0.24.*"
//    proxybridge: "nexus:com.hyphale:ProxyBridge-Bukkit:0.1.*"
//    networkspawn: "nexus:com.hyphale:NetworkSpawn-Bukkit:0.2.*"
//    commands: "nexus:com.hyphale:Commands-Bukkit:0.28.*"
//    chat: "nexus:com.hyphale:Chat-Bukkit:0.6.*"
//    inventories: "nexus:com.hyphale:Inventories-Bukkit:0.27.*"
//    serverschedule: "nexus:com.hyphale:ServerSchedule-Bukkit:0.2.*"
  }

  performance {
    #viewdistancetweaks: "https://repo.hyphale.com/plugins/viewdistancetweaks/ViewDistanceTweaks-1.5.8-SNAPSHOT.jar"
  }

}

velocity {

}

servers {
  velocity: ${velocity} {
  }

  hub: ${paper.core} {
  }

  empty: {

  }
}
